### ISSUE TITLE
How about the accuracy of your reproduction?

### ISSUE THREAD

**Issue by liming-ai** [rahulvigneswaran/Class-Balanced-Distillation-for-Long-Tailed-Visual-Recognition.pytorch#1]
Hi @rahulvigneswaran , thanks for your contribution, how about the accuracy of your reproduction? Have you ever test it or compare it with original paper?

**Comment by rahulvigneswaran** [comment]
Hey @mitming, I did test it on ImageNet-LT. I was able to match the accuracy when doing CBD with 1 teacher network. While using more than 1 teacher network, the accuracy did slightly increase but was not able to match the trend of drastic increase in accuracy.

I also tried benchmarking on CIFAR100-LT (which the paper doesn't), in which the results are promising.
