### ISSUE TITLE
Bugs in multi_runs.sh and experiments_maker.py

### ISSUE THREAD

**Issue by yufu** [rahulvigneswaran/Class-Balanced-Distillation-for-Long-Tailed-Visual-Recognition.pytorch#2]
Missing "for" in `multi_runs.sh`

**Comment by rahulvigneswaran** [comment]
@yufu Thanks for pointing it out!

**Comment by yufu** [comment]
Thanks for your response. 
Moreover, I have no idea why 2 is assigned to epoch number for all training types in line 325 of the file libs/utils/experiments_maker.py? 
I am looking forward to your reply. 

Thanks

**Comment by rahulvigneswaran** [comment]
@yufu Lines 325,326 must be removed. I used those lines to run the code quickly and check if they are working correctly. Thanks for pointing it out. I have made the necessary changes in the latest commit.

**Comment by yufu** [comment]
That makes sense. Thanks.
