### ISSUE TITLE
Dataset Related Issue: FileNotFoundError

### ISSUE THREAD

**Issue by ShirleyHe2020** [rahulvigneswaran/Class-Balanced-Distillation-for-Long-Tailed-Visual-Recognition.pytorch#4]
FileNotFoundError: [Errno 2] No such file or directory: '/DATA/datasets/ImageNet_LT/train/n01744401/n01744401_3784.JPEG'
![image](https://user-images.githubusercontent.com/63453957/144371292-aa0c6174-b630-406a-be52-c11d61ac2913.png)
![image](https://user-images.githubusercontent.com/63453957/144371647-f2372713-2107-474c-acd0-da8373d61579.png)

I uploaded all the images under /DATA/datasets/ImageNet_LT,  how do i know which images should under train/test/val?

**Comment by rahulvigneswaran** [comment]
Hi @ShirleyHe2020 , Can you go into the folder inside which you have the downloaded dataset and run the `pwd` command and post here what you get?

**Comment by ShirleyHe2020** [comment]
> Hi @ShirleyHe2020 , Can you go into the folder inside which you have the downloaded dataset and run the `pwd` command and post here what you get?

![image](https://user-images.githubusercontent.com/63453957/144775044-0ad8a663-f11b-4a93-b2a8-a41093c7b63f.png)
![image](https://user-images.githubusercontent.com/63453957/144775490-4732dbd6-d944-4055-aa86-9880b6e5e4cc.png)
![image](https://user-images.githubusercontent.com/63453957/144775631-ad749581-4540-4fbb-9b4b-5da68449daea.png)

**Comment by rahulvigneswaran** [comment]
Looks like you have the 2010 version of ImageNet. All papers in LongTail use the 2014 version. Check this https://github.com/facebookresearch/classifier-balancing#dataset

Let me know if this helps.

**Comment by ShirleyHe2020** [comment]
> Looks like you have the 2010 version of ImageNet. All papers in LongTail use the 2014 version. Check this https://github.com/facebookresearch/classifier-balancing#dataset
> 
> Let me knoHi w if this helps.

H

**Comment by ShirleyHe2020** [comment]
> Looks like you have the 2010 version of ImageNet. All papers in LongTail use the 2014 version. Check this https://github.com/facebookresearch/classifier-balancing#dataset
> 
> Let me know if this helps.

Hi Rahul, I login to ImageNet but didn't find the dataset 2014， can you plz help upload the dataset ?
