### ISSUE TITLE
What if I want to use this repo to do object detection tasks ? 

### ISSUE THREAD

**Issue by ShirleyHe2020** [rahulvigneswaran/Class-Balanced-Distillation-for-Long-Tailed-Visual-Recognition.pytorch#5]
Hi Rahul, 
Thank you for sharing this lovely repo.

Method in this paper is for image recognition,  is it possibile to update for obect detection ( classifciation + location), if yes, how can we do that ?

**Comment by rahulvigneswaran** [comment]
Am not sure as to how to port this to an image recognition setting. Perhaps you can try contacting the author of the paper.
